services:
  - type: web
    name: cooking-app-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: SUPABASE_URL
        sync: false  # Set manually in Render dashboard
      - key: SUPABASE_KEY
        sync: false  # Set manually in Render dashboard
      - key: SUPABASE_SERVICE_KEY
        sync: false  # Set manually in Render dashboard
      - key: DATABASE_URL
        sync: false  # Set manually in Render dashboard
      - key: OPENAI_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: FIREBASE_PROJECT_ID
        sync: false  # Set manually in Render dashboard
