services:
  - type: web
    name: cooking-app-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: SUPABASE_URL
        value: ${{ secrets.SUPABASE_URL }}
      - key: SUPABASE_KEY
        value: ${{ secrets.SUPABASE_ANON_KEY }}
      - key: SUPABASE_SERVICE_KEY
        value: ${{ secrets.SUPABASE_SERVICE_KEY }}
      - key: OPENAI_API_KEY
        value: ${{ secrets.OPENAI_API_KEY }}
      - key: FIREBASE_PROJECT_ID
        value: ${{ secrets.FIREBASE_PROJECT_ID }}
