// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSoS2_zeCbhEJ6iz81fd_w4ZXLY2aKYyQ',
    appId: '1:678384767745:web:1881d903c77b2db0bd0100',
    messagingSenderId: '678384767745',
    projectId: 'white-povar',
    authDomain: 'white-povar.firebaseapp.com',
    storageBucket: 'white-povar.firebasestorage.app',
    measurementId: 'G-SWG5GVGK34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeC0agp9k3m8TXxCvv_Vn0tWeMgWbCv1E',
    appId: '1:678384767745:android:0360e6dc732ec21dbd0100',
    messagingSenderId: '678384767745',
    projectId: 'white-povar',
    storageBucket: 'white-povar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_3plVkgWbu3I7G5hoXLIHBXeQvvg7WUM',
    appId: '1:678384767745:ios:2d6e67d8cbe77e0abd0100',
    messagingSenderId: '678384767745',
    projectId: 'white-povar',
    storageBucket: 'white-povar.firebasestorage.app',
    iosClientId: '678384767745-drus7apjd9r59j730qai41a8a7f2jqg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGpF-4ygseGXTVV_zA-P-VbSQiUzhJNqq',
    appId: '1:123456789:macos:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'white-povar',
    storageBucket: 'white-povar.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGpF-4ygseGXTVV_zA-P-VbSQiUzhJNqq',
    appId: '1:123456789:windows:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'white-povar',
  );
}